# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20190707_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='masters_education_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='masters_education_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
