# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20190709_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='High_School_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='High_School_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Junior_School_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Junior_School_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bachelors_education_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bachelors_education_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
