# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-16 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190616_1406'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('year', models.DateField()),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('organisation', models.CharField(blank=True, max_length=128)),
                ('position', models.CharField(blank=True, max_length=128)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile')),
            ],
        ),
    ]
