# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-16 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190616_2009'),
        ('resume', '0004_auto_20190616_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(blank=True, max_length=128, null=True)),
                ('designation', models.CharField(blank=True, max_length=128, null=True)),
                ('worked_from', models.DateField()),
                ('worked_till', models.DateField()),
                ('current', models.BooleanField(default=False)),
                ('describe', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile')),
            ],
        ),
    ]
