# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-18 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='organisation',
        ),
    ]
