# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-30 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20190620_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='worked_till',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
