# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20190630_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educations',
            name='user',
        ),
        migrations.DeleteModel(
            name='Educations',
        ),
    ]
