# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20190709_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='describe',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
