# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20190709_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='worked_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
