# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_auto_20190709_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
